### Create NumPy Array

In [3]:
import numpy as np

a = [1,2,3]
b = np.array(a)
print(b)
print(type(b))

[1 2 3]
<class 'numpy.ndarray'>


In [5]:
a = [1,2,3,'5','a',4.5]
b = np.array(a)
print(b)

['1' '2' '3' '5' 'a' '4.5']


In [10]:
a = [1,2,3,'5',4.5]
b = np.array(a,dtype = float)
print(b)

[1.  2.  3.  5.  4.5]


In [12]:
a = [1,2,3,'5',4.5]
b = np.array(a * 3)
print(b)

['1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5' '1' '2' '3' '5' '4.5']


In [15]:
b = np.ones(3,dtype = int)
b

array([1, 1, 1])

In [19]:
b = np.zeros(3,dtype = int)
b

array([0, 0, 0])

In [21]:
b = np.ones((2,3),dtype = int)
b

array([[1, 1, 1],
       [1, 1, 1]])

In [23]:
b = np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [28]:
b = np.full((3,3),5,dtype = float)
b

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [39]:
b = np.empty((2,2))
b

array([[2.12199579e-314, 0.00000000e+000],
       [4.52564132e-321, 9.35800144e-312]])

In [41]:
b = np.empty((3,4),dtype = int)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

### Create NumPy Array-2

In [44]:
b = np.identity(3,dtype = int)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [54]:
b = np.identity(3,4,dtype = int)
b

TypeError: identity() got multiple values for argument 'dtype'

In [55]:
b = np.eye(3,dtype = int)
b

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [57]:
b = np.eye(3,4,dtype = int)
b

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]])

In [59]:
b = np.random.rand(3)
b

array([0.75578342, 0.72424763, 0.26916458])

In [61]:
b = np.random.rand(3,dtype = int)
b

TypeError: rand() got an unexpected keyword argument 'dtype'

In [66]:
b = np.random.rand(10)*10
b

array([2.6783283 , 5.22587618, 6.18292258, 4.77596439, 8.88365208,
       3.74463838, 9.01564816, 9.37540871, 9.45428007, 5.19924588])

In [86]:
b = np.random.randint(1,10,10)
b

array([8, 4, 6, 7, 1, 7, 1, 7, 8, 2])

In [152]:
b = np.random.randint(10,4)
b

ValueError: low >= high

In [157]:
b = np.random.randint(2,high = None,size = None,dtype = int)
b

0

In [90]:
b = np.random.randint(10,size = (4,4))
b

array([[3, 1, 1, 4],
       [2, 9, 4, 8],
       [7, 7, 0, 1],
       [2, 2, 2, 8]])

In [93]:
b = np.arange(4)
b

array([0, 1, 2, 3])

In [94]:
b = np.arange(2,10)
b

array([2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
b = np.arange(1,10,-1)
b

array([], dtype=int32)

In [151]:
b = np.arange(2,15,7)
b

array([2, 9])

In [103]:
b = np.linspace(2,15,10)
b

array([ 2.        ,  3.44444444,  4.88888889,  6.33333333,  7.77777778,
        9.22222222, 10.66666667, 12.11111111, 13.55555556, 15.        ])

In [105]:
b = np.linspace(2,15,10,endpoint = False,dtype = int)
b

array([ 2,  3,  4,  5,  7,  8,  9, 11, 12, 13])

In [112]:
b = np.linspace(2,15,10,retstep = True,endpoint = False)
b

(array([ 2. ,  3.3,  4.6,  5.9,  7.2,  8.5,  9.8, 11.1, 12.4, 13.7]), 1.3)

In [136]:
b = np.linspace((2,15),10,endpoint = False,axis = 1)
b

array([[ 2.  ,  2.16,  2.32,  2.48,  2.64,  2.8 ,  2.96,  3.12,  3.28,
         3.44,  3.6 ,  3.76,  3.92,  4.08,  4.24,  4.4 ,  4.56,  4.72,
         4.88,  5.04,  5.2 ,  5.36,  5.52,  5.68,  5.84,  6.  ,  6.16,
         6.32,  6.48,  6.64,  6.8 ,  6.96,  7.12,  7.28,  7.44,  7.6 ,
         7.76,  7.92,  8.08,  8.24,  8.4 ,  8.56,  8.72,  8.88,  9.04,
         9.2 ,  9.36,  9.52,  9.68,  9.84],
       [15.  , 14.9 , 14.8 , 14.7 , 14.6 , 14.5 , 14.4 , 14.3 , 14.2 ,
        14.1 , 14.  , 13.9 , 13.8 , 13.7 , 13.6 , 13.5 , 13.4 , 13.3 ,
        13.2 , 13.1 , 13.  , 12.9 , 12.8 , 12.7 , 12.6 , 12.5 , 12.4 ,
        12.3 , 12.2 , 12.1 , 12.  , 11.9 , 11.8 , 11.7 , 11.6 , 11.5 ,
        11.4 , 11.3 , 11.2 , 11.1 , 11.  , 10.9 , 10.8 , 10.7 , 10.6 ,
        10.5 , 10.4 , 10.3 , 10.2 , 10.1 ]])

In [100]:
np.random.rand()

0.15308517480104045

### Output Question

a = np.array([0,1,2,3,4,5])
a.shape

### NumPy Inclusive

In [160]:
import numpy as np
b = np.linspace(9,49,dtype = int)
for i in range(len(b)-1):
    if b[i] != b[i + 1]:
        print(b[i],end = ' ')
print(b[len(b) - 1])

9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49


### Identity Matrix

In [168]:
import numpy as np
b = np.eye(5,6,dtype = int)
b

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0]])

### Cut The Rope

In [174]:
b = np.linspace(0,5,9,endpoint = False,retstep = True)
b

(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
        2.77777778, 3.33333333, 3.88888889, 4.44444444]),
 0.5555555555555556)

### Slicing And Indexing

In [176]:
import numpy as np
li = [1,2,3,4,5]
arr = np.array(li)
print(li)
print(arr)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [183]:
print(arr.data)
print(arr.shape)
print(arr.dtype)
print(arr.strides)

(5,)
int32
(4,)


In [185]:
print(li[3])
print(arr[3])
print(li[1:4])
print(arr[1:4])

4
4
[2, 3, 4]
[2 3 4]


In [180]:
li_2d = [[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]
arr_2d = np.array(li_2d)
print(li_2d)
print(arr_2d)


[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [186]:
print(arr_2d.data)
print(arr_2d.shape)
print(arr_2d.dtype)
print(arr_2d.strides)

(4, 4)
int32
(16, 4)


In [190]:
print(li_2d[2][1])
print(arr_2d[2][1])
print(arr_2d[2,1])


10
10
10


In [195]:
print(li_2d[1][0:3])
print(arr_2d[1][0:3])


[5, 6, 7]
[5 6 7]


In [209]:
print(li_2d[0:3][2])

[9, 10, 11, 12]


In [210]:
print(li_2d[0:3][3])

IndexError: list index out of range

In [211]:
x = li_2d[0:3]
print(x)
y = x[2]
print(y)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
[9, 10, 11, 12]


In [218]:
print(arr_2d[0:3,3])

[ 4  8 12]


In [220]:
print(arr_2d[2:4,1:3])
print(li_2d[2:4][1:3])

[[10 11]
 [14 15]]
[[13, 14, 15, 16]]


### Mathematical Operations for 1D Array

In [222]:
import numpy as np
li = [1,2,3,4,5]
a = np.random.randint(1,20,5)
b = np.random.randint(1,20,5)
print(li)
print(a)
print(b)

[1, 2, 3, 4, 5]
[15  4 18  1 19]
[ 6  7 11 18  5]


In [224]:
li = [i + 1 for i in li]
li

[3, 4, 5, 6, 7]

In [227]:
a = a + 1
a

array([18,  7, 21,  4, 22])

In [229]:
b = b + 1
b

array([ 8,  9, 13, 20,  7])

In [231]:
c = a + b
c

array([26, 16, 34, 24, 29])

In [233]:
d = a - b 
d

array([ 10,  -2,   8, -16,  15])

In [236]:
e = a * b
e

array([144,  63, 273,  80, 154])

In [238]:
f = a / b
f

array([2.25      , 0.77777778, 1.61538462, 0.2       , 3.14285714])

In [240]:
g = a // b
g

array([2, 0, 1, 0, 3], dtype=int32)

In [242]:
h = a ** b
h

array([-1864941312,    40353607,   583011173,           0, -1800609408],
      dtype=int32)

In [245]:
print(a)
print(a.sum())
print(a.mean())
print(a.min())
print(a.argmin())
print(a.max())
print(a.argmax())

[18  7 21  4 22]
72
14.4
4
3
22
4


In [247]:
print(a)
print(b)

[18  7 21  4 22]
[ 8  9 13 20  7]


Relational Operators

In [249]:
a > b

array([ True, False,  True, False,  True])

In [251]:
a < b

array([False,  True, False,  True, False])

In [253]:
a == b

array([False, False, False, False, False])

In [255]:
print(np.logical_or(a,b))
print(np.logical_and(a,b))

[ True  True  True  True  True]
[ True  True  True  True  True]


In [260]:
a[2] = 0
print(a)
print(np.logical_not(a)) #Because all non-zero values taking their not

[ 2  7  0  4 22]
[False False  True False False]


### Mathematical Operations for 2-D Arrays

### Boolean Indexing for 1-D Arrays

In [262]:
import numpy as np
a = np.array(['t','b','r','d','e','f','z','a'])
b = np.random.randint(1,20,8)
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[ 7 16  9  8 19 16  9  1]


In [264]:
print(b > 10)

[False  True False False  True  True False False]


In [267]:
bool_arr = b > 10
print(bool_arr)
new_arr = b[bool_arr]
print(new_arr)

[False  True False False  True  True False False]
[16 19 16]


In [270]:
new_arr = b[b > 10]
new_arr

array([16, 19, 16])

In [276]:
new_arr = b[(b > 10) & (b < 18)]
new_arr

array([16, 16])

In [279]:
print(b)
c = b
c

[ 7 16  9  8 19 16  9  1]


array([ 7, 16,  9,  8, 19, 16,  9,  1])

In [282]:
c[:3] = 19
print(c)
c[c > 15] = 100
c

[ 19  19  19   8 100 100   9   1]


array([100, 100, 100,   8, 100, 100,   9,   1])

In [284]:
print(b)

[100 100 100   8 100 100   9   1]


In [286]:
print(b[b == 100])

[100 100 100 100 100]


In [289]:
ind = np.where(b == 100)
ind

(array([0, 1, 2, 4, 5], dtype=int64),)

In [291]:
print(a)
print(b)

['t' 'b' 'r' 'd' 'e' 'f' 'z' 'a']
[100 100 100   8 100 100   9   1]


In [294]:
ind = np.where(b == 100)
print(ind)
print(a[ind])

(array([0, 1, 2, 4, 5], dtype=int64),)
['t' 'b' 'r' 'e' 'f']


#### Replace Max

In [299]:
import numpy as np
arr = np.random.randint(2,20,10)
print(arr)
ma = arr.max()
ind = np.where(arr == ma)
arr[ind] = 0
for i in arr:
    print(i)

[ 8  8 18 14 12  9 17  6  8  7]
8
8
0
14
12
9
17
6
8
7


#### Negate Elements

In [302]:
import numpy as np
arr = np.arange(1,11)
arr[(arr > 2) & (arr < 9)] = -arr[(arr > 2) & (arr < 9)]
for i in arr:
    print(i)

1
2
-3
-4
-5
-6
-7
-8
9
10


#### Height

In [304]:
import numpy as np
age=np.array([15,17,19,20,14,21,16,19,13,20,22,23,21,16,18,19,20,15,17,18])
height=np.array([156,144,180,162,152,157,154,155,151,150,158,179,126,182,183,154,159,160,172,149])
for i in range(len(age)):
    if height[i] > 155:
        print(age[i],height[i])

15 156
19 180
20 162
21 157
22 158
23 179
16 182
18 183
20 159
15 160
17 172


### Boolean Indexing for 2-D Arrays

In [307]:
import numpy as np
a = np.random.randint(1,30,(5,6))
print(a)

[[ 9 27 27 12  5  8]
 [11  3 16 19 21 21]
 [ 7 13 19  8  6 23]
 [17 27 14 11 24 11]
 [27  4 17 27  8 15]]


In [310]:
bool_arr = a > 20
print(bool_arr)

[[False  True  True False False False]
 [False False False False  True  True]
 [False False False False False  True]
 [False  True False False  True False]
 [ True False False  True False False]]


In [314]:
ans = a[bool_arr]
print(ans)

[27 27 21 21 23 27 24 27 27]


In [316]:
b = a
print(a)

[[ 9 27 27 12  5  8]
 [11  3 16 19 21 21]
 [ 7 13 19  8  6 23]
 [17 27 14 11 24 11]
 [27  4 17 27  8 15]]


In [318]:
b[bool_arr] = 100
print(b)

[[  9 100 100  12   5   8]
 [ 11   3  16  19 100 100]
 [  7  13  19   8   6 100]
 [ 17 100  14  11 100  11]
 [100   4  17 100   8  15]]


In [322]:
c = np.random.randint(1,10,(2,2))
print(c)

[[5 6]
 [7 5]]


In [337]:
c_bool = np.array([[True,False],[False,True],[True,True]])
print(c_bool)

[[ True False]
 [False  True]
 [ True  True]]


In [329]:
#print(c[c_bool])

In [331]:
print(b)

[[  9 100 100  12   5   8]
 [ 11   3  16  19 100 100]
 [  7  13  19   8   6 100]
 [ 17 100  14  11 100  11]
 [100   4  17 100   8  15]]


In [333]:
bool_arr = b[:,3] == 100
print(bool_arr)

[False False False False  True]


In [336]:
b[bool_arr,3] = 99
print(b)

[[  9 100 100  12   5   8]
 [ 11   3  16  19 100 100]
 [  7  13  19   8   6 100]
 [ 17 100  14  11 100  11]
 [100   4  17  99   8  15]]


#### Sort by Column

In [341]:
import numpy as np
b = np.array( [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
rev_b = b[::-1]
print(rev_b)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


In [342]:
import numpy as np
b = np.array( [[21,20,19,18,17],[16,15,14,13,12],[11,10,9,8,7],[6,5,4,3,2]])
ans = b[b[:,1].argsort()]
print(ans)

[[ 6  5  4  3  2]
 [11 10  9  8  7]
 [16 15 14 13 12]
 [21 20 19 18 17]]


### BroadCasting

In [344]:
import numpy as np
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3,3))
print(x)
print(y)

[[4 8 6]
 [2 9 8]
 [6 1 7]]
[[6 3 8]
 [6 8 1]
 [9 3 8]]


In [346]:
ans = x - y
print(ans)

[[-2  5 -2]
 [-4  1  7]
 [-3 -2 -1]]


In [347]:
x = np.random.randint(1,10,(3,3))
y = np.random.randint(1,10,(3))
print(x)
print(y)

[[1 9 1]
 [1 6 2]
 [4 6 4]]
[4 4 4]


In [348]:
ans = x - y
print(ans)

[[-3  5 -3]
 [-3  2 -2]
 [ 0  2  0]]


In [350]:
x = np.random.randint(1,10,(3,2))
y = np.random.randint(1,10,(2,3))
print(x)
print(y)

[[9 6]
 [4 5]
 [4 2]]
[[3 2 2]
 [7 8 2]]


In [352]:
ans = x - y
print(ans)

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [357]:
y = np.transpose(y)
print(y)
ans = x - y
print(ans)

[[3 7]
 [2 8]
 [2 2]]
[[ 6 -1]
 [ 2 -3]
 [ 2  0]]


In [361]:
a=np.array([[0,1],[2,3]])
print(np.resize(a,(2,3)))
print(np.resize(a,(3,4)))
print(np.resize(a,(2,4)))

[[0 1 2]
 [3 0 1]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 1 2 3]
 [0 1 2 3]]


In [364]:

import numpy as np
 
v = np.array([12, 24, 36]) 
w = np.array([45, 55])   
 
# To compute an outer product we first
# reshape v to a column vector of shape 3x1
# then broadcast it against w to yield an output
# of shape 3x2 which is the outer product of v and w
print(np.reshape(v, (3, 1)) * w)

[[ 540  660]
 [1080 1320]
 [1620 1980]]


In [371]:
a = np.arange(6).reshape((3, 2))
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [374]:
x = np.random.randint(1,10,(1,3))
y = np.random.randint(1,10,(1))
ans = x - y
print(x)
print(y)
print(ans)

[[8 1 9]]
[2]
[[ 6 -1  7]]


In [376]:
x = np.random.randint(1,10,(1,3))
y = np.random.randint(1,10,(3,1))
ans = x - y
print(x)
print(y)
print(ans)

[[5 8 9]]
[[2]
 [7]
 [4]]
[[ 3  6  7]
 [-2  1  2]
 [ 1  4  5]]


In [383]:
x = np.random.randint(1,10,(2,3))
y = np.random.randint(1,10,(3,1))
x = np.transpose(x)
ans = x - y
print(ans)

[[-1 -6]
 [-1  0]
 [ 3  0]]


### Example

In [385]:
import numpy as np 
import csv

file_obj = open("Datasets/year2017.csv")
data = csv.DictReader(file_obj,skipinitialspace = True)

killed = []
wounded = []
country = []
for row in data:
    killed.append(row['Killed'])
    wounded.append(row['Wounded'])
    country.append(row['Country'])
np_killed = np.array(killed)
np_wounded = np.array(wounded)

np_killed[np_killed == ''] = '0.0'
np_wounded[np_wounded == ''] = '0.0'

np_killed = np.array(np_killed,dtype = float)
np_wounded = np.array(np_wounded,dtype = float)

killed_wounded = np_killed + np_wounded
np_country = np.array(country)
bool_arr = np_country == 'India'
ans = killed_wounded[bool_arr]
print(np.sum(ans))
print(np.sum(killed_wounded))

FileNotFoundError: [Errno 2] No such file or directory: 'Datasets/year2017.csv'